### ISSUE TITLE
gunicorn 설치 및 연동

### ISSUE THREAD

**Issue by JSpiner** [JSpiner/Soma_SlackBot_taja#132]

**Comment by TWpower** [comment]
- gunicorn 명령어
gunicorn -w8 --certfile=../../SSL_key/last.crt --keyfile=../../SSL_key/ssoma.key app:app -b 0.0.0.0:20000
-w는 프로세스 수, --certfile은 crt 파일경로, --keyfile은 key 파일경로, -b는 ip와포트

- app.py에 아래처럼 코드 변경하여야함
`
if __name__ == '__main__':
   app.run(debug = True)`
