### ISSUE TITLE
gunicorn 사용을 위한 app.py코드 변경하기

### ISSUE THREAD

**Issue by TWpower** [JSpiner/Soma_SlackBot_taja#139]
- app.py에 아래처럼 코드 변경하기
  'if **name** == '**main**':
  app.run(debug = True)'
- gunicorn 명령어
  gunicorn -w8 --certfile=../../SSL_key/last.crt --keyfile=../../SSL_key/ssoma.key app:app -b 0.0.0.0:20000
  -w는 프로세스 수, --certfile은 crt 파일경로, --keyfile은 key 파일경로, -b는 ip와포트

**Comment by JSpiner** [comment]
요부분 스크립트코드로 만들어놓으면 편할거같아요

**Comment by JSpiner** [comment]
newrlic이랑 연동
See also: Python Agent Integration

Execute your WSGI server by adding some New Relic configurations like this:

NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program command options
In a few minutes, your application will send data to New Relic. Once New Relic receives the data, your application will be listed here. This page will look similar to: Python-app-index-sample

**Comment by JSpiner** [comment]
https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-integration

**Comment by TWpower** [comment]
OK~
