### ISSUE TITLE
게임 텍스트에 이모티콘이 있을경우, 자동변환되어 비교가 불가능한 문제

### ISSUE THREAD

**Issue by JSpiner** [JSpiner/Soma_SlackBot_taja#19]
ex)
제시어 : 안녕하세요 :)
유저입력 : 안녕하세요 :)    
':)' 이 이모티콘으로 자동 변환되면서 ':slightly_smiling_face'로 자동변환되어 정확도가 45%로 떨어짐

**Comment by TWpower** [comment]
하.... 이건 또 무슨 일이래...

**Comment by TWpower** [comment]
이거 같은 경우에는 제시어에서 빼는 방향은 어떨까? :)와 같은 부분이 들어간건 문제로 내지 않게
